name: AppIdeasMC
version: ${project.version}
main: datrat.appideasmc.AppIdeasMain
api-version: 1.16
authors: [ DatRat ]
description: Applying some application ideas on bukkit/spigot/paper.

commands:
  bin2dec:
    description: Converts binary numbers into decimal numbers.
    usage: /bin2dec (binary)
  calc:
    description: Executes simple calculations.
    usage: /calc (x) (operator) (y)
  rng:
    description: Generates a random number between x and y
    usage: /rng (x) (y)
  loremipsum:
    description: Generates custom amounts of Lorem Ipsum paragraphs.
    usage: /loremipsum (amount)
  fly:
    description: Turns your flight on and off.
    usage: /fly (on/off)
  util:
    description: Bunch of util commands.
    usage: /util (util)